en:
  languageCode: en
  languageName: English
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  contentDir: content/en

# Uncomment for multilingual sites, and customize the following config.
ar:
  languageCode: ar
  languageName: العربية
  languagedirection: rtl
  contentDir: content/ar
  title: مدوّنة رامي
# zh:
#   languageCode: zh
#   languageName: 简体中文
#   contentDir: content/zh
#   title: 中文标题